/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalVoiceRouteImport } from './routes/portal.voice'
import { Route as PortalSmartCityRouteImport } from './routes/portal.smart-city'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalSchemeAiRouteImport } from './routes/portal.scheme-ai'
import { Route as PortalRuralRouteImport } from './routes/portal.rural'
import { Route as PortalReportsRouteImport } from './routes/portal.reports'
import { Route as PortalMunicipalRouteImport } from './routes/portal.municipal'
import { Route as PortalHelplineRouteImport } from './routes/portal.helpline'
import { Route as PortalGrievancesRouteImport } from './routes/portal.grievances'
import { Route as PortalElectionRouteImport } from './routes/portal.election'
import { Route as PortalDisasterRouteImport } from './routes/portal.disaster'
import { Route as PortalCitizensRouteImport } from './routes/portal.citizens'
import { Route as PortalAnalyticsRouteImport } from './routes/portal.analytics'
import { Route as PortalAgricultureRouteImport } from './routes/portal.agriculture'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVoiceRoute = PortalVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSmartCityRoute = PortalSmartCityRouteImport.update({
  id: '/smart-city',
  path: '/smart-city',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSchemeAiRoute = PortalSchemeAiRouteImport.update({
  id: '/scheme-ai',
  path: '/scheme-ai',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRuralRoute = PortalRuralRouteImport.update({
  id: '/rural',
  path: '/rural',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMunicipalRoute = PortalMunicipalRouteImport.update({
  id: '/municipal',
  path: '/municipal',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHelplineRoute = PortalHelplineRouteImport.update({
  id: '/helpline',
  path: '/helpline',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGrievancesRoute = PortalGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => PortalRoute,
} as any)
const PortalElectionRoute = PortalElectionRouteImport.update({
  id: '/election',
  path: '/election',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDisasterRoute = PortalDisasterRouteImport.update({
  id: '/disaster',
  path: '/disaster',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCitizensRoute = PortalCitizensRouteImport.update({
  id: '/citizens',
  path: '/citizens',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnalyticsRoute = PortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAgricultureRoute = PortalAgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/agriculture': typeof PortalAgricultureRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/citizens': typeof PortalCitizensRoute
  '/portal/disaster': typeof PortalDisasterRoute
  '/portal/election': typeof PortalElectionRoute
  '/portal/grievances': typeof PortalGrievancesRoute
  '/portal/helpline': typeof PortalHelplineRoute
  '/portal/municipal': typeof PortalMunicipalRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/rural': typeof PortalRuralRoute
  '/portal/scheme-ai': typeof PortalSchemeAiRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/smart-city': typeof PortalSmartCityRoute
  '/portal/voice': typeof PortalVoiceRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/agriculture': typeof PortalAgricultureRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/citizens': typeof PortalCitizensRoute
  '/portal/disaster': typeof PortalDisasterRoute
  '/portal/election': typeof PortalElectionRoute
  '/portal/grievances': typeof PortalGrievancesRoute
  '/portal/helpline': typeof PortalHelplineRoute
  '/portal/municipal': typeof PortalMunicipalRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/rural': typeof PortalRuralRoute
  '/portal/scheme-ai': typeof PortalSchemeAiRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/smart-city': typeof PortalSmartCityRoute
  '/portal/voice': typeof PortalVoiceRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/agriculture': typeof PortalAgricultureRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/citizens': typeof PortalCitizensRoute
  '/portal/disaster': typeof PortalDisasterRoute
  '/portal/election': typeof PortalElectionRoute
  '/portal/grievances': typeof PortalGrievancesRoute
  '/portal/helpline': typeof PortalHelplineRoute
  '/portal/municipal': typeof PortalMunicipalRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/rural': typeof PortalRuralRoute
  '/portal/scheme-ai': typeof PortalSchemeAiRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/smart-city': typeof PortalSmartCityRoute
  '/portal/voice': typeof PortalVoiceRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/signup'
    | '/sitemap.xml'
    | '/portal/admin'
    | '/portal/agriculture'
    | '/portal/analytics'
    | '/portal/citizens'
    | '/portal/disaster'
    | '/portal/election'
    | '/portal/grievances'
    | '/portal/helpline'
    | '/portal/municipal'
    | '/portal/reports'
    | '/portal/rural'
    | '/portal/scheme-ai'
    | '/portal/settings'
    | '/portal/smart-city'
    | '/portal/voice'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/portal/admin'
    | '/portal/agriculture'
    | '/portal/analytics'
    | '/portal/citizens'
    | '/portal/disaster'
    | '/portal/election'
    | '/portal/grievances'
    | '/portal/helpline'
    | '/portal/municipal'
    | '/portal/reports'
    | '/portal/rural'
    | '/portal/scheme-ai'
    | '/portal/settings'
    | '/portal/smart-city'
    | '/portal/voice'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/signup'
    | '/sitemap.xml'
    | '/portal/admin'
    | '/portal/agriculture'
    | '/portal/analytics'
    | '/portal/citizens'
    | '/portal/disaster'
    | '/portal/election'
    | '/portal/grievances'
    | '/portal/helpline'
    | '/portal/municipal'
    | '/portal/reports'
    | '/portal/rural'
    | '/portal/scheme-ai'
    | '/portal/settings'
    | '/portal/smart-city'
    | '/portal/voice'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/voice': {
      id: '/portal/voice'
      path: '/voice'
      fullPath: '/portal/voice'
      preLoaderRoute: typeof PortalVoiceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/smart-city': {
      id: '/portal/smart-city'
      path: '/smart-city'
      fullPath: '/portal/smart-city'
      preLoaderRoute: typeof PortalSmartCityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/scheme-ai': {
      id: '/portal/scheme-ai'
      path: '/scheme-ai'
      fullPath: '/portal/scheme-ai'
      preLoaderRoute: typeof PortalSchemeAiRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/rural': {
      id: '/portal/rural'
      path: '/rural'
      fullPath: '/portal/rural'
      preLoaderRoute: typeof PortalRuralRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports': {
      id: '/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/municipal': {
      id: '/portal/municipal'
      path: '/municipal'
      fullPath: '/portal/municipal'
      preLoaderRoute: typeof PortalMunicipalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/helpline': {
      id: '/portal/helpline'
      path: '/helpline'
      fullPath: '/portal/helpline'
      preLoaderRoute: typeof PortalHelplineRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/grievances': {
      id: '/portal/grievances'
      path: '/grievances'
      fullPath: '/portal/grievances'
      preLoaderRoute: typeof PortalGrievancesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/election': {
      id: '/portal/election'
      path: '/election'
      fullPath: '/portal/election'
      preLoaderRoute: typeof PortalElectionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/disaster': {
      id: '/portal/disaster'
      path: '/disaster'
      fullPath: '/portal/disaster'
      preLoaderRoute: typeof PortalDisasterRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/citizens': {
      id: '/portal/citizens'
      path: '/citizens'
      fullPath: '/portal/citizens'
      preLoaderRoute: typeof PortalCitizensRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/analytics': {
      id: '/portal/analytics'
      path: '/analytics'
      fullPath: '/portal/analytics'
      preLoaderRoute: typeof PortalAnalyticsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/agriculture': {
      id: '/portal/agriculture'
      path: '/agriculture'
      fullPath: '/portal/agriculture'
      preLoaderRoute: typeof PortalAgricultureRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalAgricultureRoute: typeof PortalAgricultureRoute
  PortalAnalyticsRoute: typeof PortalAnalyticsRoute
  PortalCitizensRoute: typeof PortalCitizensRoute
  PortalDisasterRoute: typeof PortalDisasterRoute
  PortalElectionRoute: typeof PortalElectionRoute
  PortalGrievancesRoute: typeof PortalGrievancesRoute
  PortalHelplineRoute: typeof PortalHelplineRoute
  PortalMunicipalRoute: typeof PortalMunicipalRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalRuralRoute: typeof PortalRuralRoute
  PortalSchemeAiRoute: typeof PortalSchemeAiRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalSmartCityRoute: typeof PortalSmartCityRoute
  PortalVoiceRoute: typeof PortalVoiceRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalAgricultureRoute: PortalAgricultureRoute,
  PortalAnalyticsRoute: PortalAnalyticsRoute,
  PortalCitizensRoute: PortalCitizensRoute,
  PortalDisasterRoute: PortalDisasterRoute,
  PortalElectionRoute: PortalElectionRoute,
  PortalGrievancesRoute: PortalGrievancesRoute,
  PortalHelplineRoute: PortalHelplineRoute,
  PortalMunicipalRoute: PortalMunicipalRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalRuralRoute: PortalRuralRoute,
  PortalSchemeAiRoute: PortalSchemeAiRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalSmartCityRoute: PortalSmartCityRoute,
  PortalVoiceRoute: PortalVoiceRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
